# Generated by Django 2.2.18 on 2021-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_predictedanomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedanomaly',
            name='frame1',
            field=models.ImageField(max_length=1000, null='true', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='predictedanomaly',
            name='frame2',
            field=models.ImageField(max_length=1000, null='true', upload_to='images'),
        ),
    ]
